### ISSUE TITLE
Warnings on startup

### ISSUE THREAD

**Issue by rethab** [playframework/play-scala-starter-example#44]
When I run this application, I get a few warning messages:
```[warn] p.a.m.DefaultUrlEncodedCookieDataCodec - Cookie failed message authentication check```

What exactly is missing here?

Thanks!

**Comment by wsargent** [comment]
Can you include the full logs from startup?  Probably what's happening here is that you've got another session cookie from another application, but it's hard to tell without more information.

**Comment by rethab** [comment]
Thanks for the hint with the other session cookie, that seems to be it. I have several applications running..

I have tried to use a different cookie name, by setting `play.http.session.cookieName` and the warning disappeared.

Thanks!
