### ISSUE TITLE
[error] Not a valid command: g8Scaffold

### ISSUE THREAD

**Issue by 0x6C38** [playframework/play-scala-starter-example#68]
I'm trying to follow [play's documentation](https://www.playframework.com/documentation/2.6.x/Tutorials#Play-Seeds) which instructs to:

> Type g8Scaffold form from sbt to create the scaffold controller, template and tests needed to process a form.

But after creating a brand new project via `sbt new playframework/play-scala-seed.g8` running `sbt g8Scaffold form` yields an error:

> [info] Loading settings from plugins.sbt ...
> [info] Loading global plugins from /home/ds/.sbt/1.0/plugins
> [info] Loading settings from plugins.sbt,scaffold.sbt ...
> [info] Loading project definition from /path/to/myproject/project
> [info] Loading settings from build.sbt ...
> [info] Set current project to myproject (in build file:/path/to/myproject)
> [error] Not a valid command: g8Scaffold
> [error] Not a valid project ID: g8Scaffold
> [error] Expected ':' (if selecting a configuration)
> [error] Not a valid key: g8Scaffold
> [error] g8Scaffold
> [error]           ^
> [INFO] [12/25/2017 12:52:25.545] [Thread-2] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
> sbt g8Scaffold form  39.21s user 0.86s system 348% cpu 11.483 total
> 

I'm on Arch Linux but the same happens on Windows 10.

**Comment by wsargent** [comment]
It looks like the plugin responsible for adding `g8Scaffold` functionality:

https://github.com/playframework/play-scala-seed.g8/blob/2.6.x/src/main/g8/project/scaffold.sbt

has been commented out as it doesn't work with sbt 1.0.

**Comment by SethTisue** [comment]
@gmethvin?

**Comment by llarsson** [comment]
Can either the documentation or the root cause of this bug be fixed, then? :) I am trying to play with Play, and this is a quite annoying hurdle for newcomers to the framework.

**Comment by SethTisue** [comment]
@marcospereira ?

**Comment by marcospereira** [comment]
Hey @SethTisue, thanks for the heads up.

It looks like we have a new release of `sbt-giter8-scaffold` (0.11.0-M3) which [has support for sbt 1.0](https://github.com/foundweekends/giter8/pull/350). Anyway, since this still a milestone release, I think it would be better to update the documentation to remove `g8Scaffold`. As soon as we have a final release, we can update both the seed and the docs again.

**Comment by marcospereira** [comment]
See https://github.com/playframework/playframework/pull/8235.

I'm now watching https://github.com/foundweekends/giter8 so that we can update the docs again when there is a new final release supporting sbt 1.x.
