### ISSUE TITLE
Gradle dist command does not work as expected

### ISSUE THREAD

**Issue by kiran002** [playframework/play-scala-starter-example#76]
Hi Everyone,

It seems to me that the command, `gradle dist` , does not produce the same output as `./sbt dist` . The archive that the gradle produces contains a shell script that does not accept any command line arguments. Where as, the same works with sbt.

Steps to reproduce: 

```bash
git clone https://github.com/playframework/play-scala-starter-example.git
cd play-scala-starter-example/
./gradlew dist
cd buid/distributions
unzip playBinary.zip
playBinary/bin/playBinary  -Dplay.http.secret.key='abcccc'
```

upon running the final command i get the error

`Bad root server path: /home/ec2-user/test/play-scala-starter-example/build/distributions/-Dplay.http.secret.key=abcccc`

where as the same steps when performed with `sbt dist`, it works perfectly fine. Would be great if you could update the gradle script, so that it also works in the future.

I did some analysis and also found that exception is raised in the following file, when project.server.dir is null

https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala

**Comment by marcospereira** [comment]
> Would be great if you could update the gradle script, so that it also works in the future.

I would say that this is a problem with Gradle plugin instead. It would be better to solve the problem there instead of forcing every user to write additional configuration. It should just work out-of-the-box, so it may be better to open an issue there.

In the meantime, a possible work around is to use `PLAY_BINARY_OPTS` env var to add the necessary parameters. For example:

```bash
export PLAY_BINARY_OPTS="-Dplay.http.secret.key='abcccc'"
./playBinary/bin/playBinary
```

**Comment by kiran002** [comment]
Ya that makes sense, I will create the issue at the plugin repo. 

Thanks for the workaround, I will close this issue now.
